M48
; DRILL file {KiCad 8.0.8-8.0.8-0~ubuntu24.04.1} date 2025-02-01T12:16:23-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-01T12:16:23-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8-8.0.8-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X139.322Y-105.202
X139.322Y-110.982
M30
